### ISSUE TITLE
Docs not showing up 

### ISSUE THREAD

**Issue by FrozenDroid** [drone-os/drone-stm32-map#7]
Hi, I saw that in the peripheral subcrates, in the macros, documentation is written for the components of those peripherals.
However, I can't find the documentation in the resulting `just doc` anywhere..

**Comment by valff** [comment]
Hi. The crate consists of `reg`, `thr`, and `periph` modules. The docs for `reg` and `thr` are intentionally turned off, otherwise they would take several gigabytes. These modules are auto-generated, so there is not much value in documenting them. You can check `drone_cortex_m::map` docs to get an idea of what the API looks like. However `periph` module docs are available.

BTW pre-generated docs are hosted here: https://api.drone-os.com/drone-stm32-map/0.11/drone_stm32_map/

**Comment by FrozenDroid** [comment]
Yeah I see, but for example, I'm not seeing https://github.com/drone-os/drone-stm32-map/blob/master/src/periph/gpio/lib.rs#L1080 show up anywhere.

**Comment by valff** [comment]
Now I see the issue. Thank you for reporting. Fixing it.
